name: build

on: 
  push:
    tags:
      - '*'
jobs:
  label:
    runs-on: macos
    steps:
      - uses: olegtarasov/get-tag@v1
        id: tagName
      - name: GET TAG NAME 
        run: |
              echo "::set-env name=TAG_NAME::${{ steps.tagName.outputs.tag  }}"
              
      - uses: actions/checkout@v1
      - name: GET TAG SHA
        run: |
              echo "::set-env name=TAG_SHA::$(git rev-parse ${{ env.TAG_NAME }})"
              
      - name: xcode-select 
        run: sudo xcode-select --switch /Applications/Xcode_11.3.app
        
      - name: CREATE DIR
        run: |
              mkdir archive
      
      - name: BUILD APP
        run: |
              xcodebuild -project './ActionsMacAppBuild/ActionsMacAppBuild.xcodeproj' -config Release -scheme 'ActionsMacAppBuild' CODE_SIGN_IDENTITY="-" -archivePath ./archive archive

      - name: EXPORT APP
        run: |
              cd archive |
              ls
