name: build

on: 
  push:
    tags:
      - '*'
jobs:
  label:
    runs-on: macos
    steps:
      - uses: olegtarasov/get-tag@v1
        id: tagName
      - name: GET TAG NAME 
        run: |
              echo "::set-env name=TAG_NAME::${{ steps.tagName.outputs.tag  }}"
              
      - uses: actions/checkout@v1
      - name: GET TAG SHA
        run: |
              echo "::set-env name=TAG_SHA::$(git rev-parse ${{ env.TAG_NAME }})"
              
      - name: xcode-select 
        run: sudo xcode-select --switch /Applications/Xcode_11.3.app
        
      - name: CREATE DIR
        run: |
              mkdir archive
      
      - name: BUILD APP
        run: |
              xcodebuild -project './ActionsMacAppBuild/ActionsMacAppBuild.xcodeproj' -config Develop -scheme 'ActionsMacAppBuild' -archivePath ./archive/ActionsMacAppBuild archive
      - name: ZIP APP
        run: |
              zip ActionsMacAppBuild -r ./archive/ActionsMacAppBuild.xcarchive/Products/Applications/ActionsMacAppBuild.app
      
      - name: UPLOAD APP
        run: |
              curl -v -H 'Content-Type:application/zip; charset=UTF-8' -X POST --data-binary "./ActionsMacAppBuild.zip" -d '{"name":"ActionsMacAppBuild.zip"}' https://api.github.com/DIO0550/ActionsMacAppBuild/releases/${{ env.TAG_NAME }}/assets?access_token=${{ secrets.GITHUB_TOKEN }}
