name: build

on: 
  push:
    tags:
      - '*'
jobs:
  label:
    runs-on: macos
    steps:
      - uses: olegtarasov/get-tag@v1
        id: tagName
      - name: GET TAG NAME 
        run: |
              echo "::set-env name=TAG_NAME::${{ steps.tagName.outputs.tag  }}"
              
      - uses: actions/checkout@v1
      - name: GET TAG SHA
        run: |
              echo "::set-env name=TAG_SHA::$(git rev-parse ${{ env.TAG_NAME }})"
              
      - name: xcode-select 
        run: sudo xcode-select --switch /Applications/Xcode_11.3.app
        
      - name: CREATE DIR
        run: |
              mkdir archive
      
      - name: BUILD APP
        run: |
              xcodebuild -project './ActionsMacAppBuild/ActionsMacAppBuild.xcodeproj' -config Develop -scheme 'ActionsMacAppBuild' -archivePath ./archive/ActionsMacAppBuild archive
      - name: ZIP APP
        run: |
              zip ActionsMacAppBuild -r ./archive/ActionsMacAppBuild.xcarchive/Products/Applications/ActionsMacAppBuild.app
      
      - name: UPLOAD APP
        run: |
              curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.manifold-preview" \
              -H "Content-Type: application/zip" \
              --data-binary @./ActionsMacAppBuild.zip \
              "https://uploads.github.com/repos/${{secrets.GITHUB_REPOSITORY}}/releases/${{ env.TAG_NAME }}/assets?name=ActionsMacAppBuild.zip"
